name = "VisualizeULPError"
uuid = "f0be587d-0f08-4cfc-9252-462b7400eb81"
version = "1.0.0"
authors = ["Neven Sajko <s@purelymail.com>"]

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"

[compat]
Cairo = "1.1.1"
Fontconfig = "0.4.1"
Gadfly = "1.4.1"
julia = "1.10"

[apps.visualize_ulp_error]
