name = "VisualizeULPError"
uuid = "f0be587d-0f08-4cfc-9252-462b7400eb81"
version = "2.0.0"
authors = ["Neven Sajko <s@purelymail.com>"]

[deps]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"

[compat]
Gadfly = "1.4.1"
julia = "1.10"

[apps.visualize_ulp_error]
